### ISSUE TITLE
Renewed certificates are not reloaded by nginx-ingress

### ISSUE THREAD

**Issue by simonswine** [jetstack/kube-lego#1]
File a PR against nginx-ingress-controller

**Comment by devth** [comment]
Until this is fixed, is there a known way to manually force nginx to reload renewed certs?

**Comment by simonswine** [comment]
@devth I think it works for me with my custom built image: [simonswine/nginx-ingress-controller:0.0.2](https://hub.docker.com/r/simonswine/nginx-ingress-controller/tags/)

But it's not yet merged to the upstream nginx-ingress-controller

**Comment by devth** [comment]
@simonswine cool, thanks! Is there a PR I can subscribe to?

**Comment by devth** [comment]
Never mind, found it! https://github.com/kubernetes/contrib/pull/1063

**Comment by aledbf** [comment]
@simonswine fixed and available in `gcr.io/google_containers/nginx-ingress-controller:0.8.1`

**Comment by simonswine** [comment]
0.0.4 contains supports upstream nginx and reloads correctly
