### ISSUE TITLE
Publish 0.1.4

### ISSUE THREAD

**Issue by naerymdan** [jetstack/kube-lego#109]
Might have a lot of issues still open, but current 0.1.3 does not work on GCE while building master does, please consider simply publishing a 0.1.4-beta if needs be so we can more easily use this awesome tool.

**Comment by bbzg** [comment]
Trying to use GCE loadbalancer on 0.1.3 doesn't seem to work for me (following the example in this git). If 0.1.4. does indeed work, that would be great.

**Comment by bbzg** [comment]
I tried building from master, but kube-lego started hammering letsencrypt and finally I got:

```
time="2017-03-31T20:36:06Z" level=info msg="authorization successful" context=acme domain=***
time="2017-03-31T20:36:06Z" level=debug msg="got authorization: &{URI:https://acme-v01.api.letsencrypt.org/acme/challenge/*** Status:valid Identifier:{Type: Value:} Challenges:[] Combinations:[]}" context=acme domain=***
time="2017-03-31T20:36:06Z" level=info msg="authorization successful" context=acme domain=***
time="2017-03-31T20:36:06Z" level=debug msg="got authorization: &{URI:https://acme-v01.api.letsencrypt.org/acme/challenge/*** Status:valid Identifier:{Type: Value:} Challenges:[] Combinations:[]}" context=acme domain=***
time="2017-03-31T20:36:06Z" level=info msg="authorization successful" context=acme domain=***
time="2017-03-31T20:36:06Z" level=error msg="Error while processing certificate requests: error getting certificate: 429 urn:acme:error:rateLimited: Error creating new cert :: Too many certificates already issued for exact set of domains: ***,***,***" context=kubelego

```

¯\_(ツ)_/¯

Not sure, but does this mean I can't try again for a week? =)

**Comment by ankon** [comment]
> Not sure, but does this mean I can't try again for a week? =)

You probably should use the staging environment while testing -- I did the same mistake and had to wait a while. 
With that said though: if you add a different (dummy) host to the TLS section of the ingress you should be able to request certificates again, as that counts as a different certificate. See https://letsencrypt.org/docs/rate-limits/ for details.

**Comment by gianrubio** [comment]
There's a canary build, build from master branch, named ```canary```

https://hub.docker.com/r/jetstack/kube-lego/tags/

**Comment by webwurst** [comment]
Release is out https://github.com/jetstack/kube-lego/releases/tag/0.1.4

**Comment by munnerz** [comment]
Closing now as both 0.1.4 and 0.1.5 are out! 😄
