### ISSUE TITLE
Make RSA key size configurable

### ISSUE THREAD

**Issue by InAnimaTe** [jetstack/kube-lego#111]
Right now, the RSA Key Size is [hardcoded](https://github.com/jetstack/kube-lego/blob/84d1eec4de97b326c4f9ea9812b8c5539b2121f1/pkg/kubelego_const/consts.go#L7) as a constant value. This issue is a request to get that made to be modifiable via environment variable as something like `LEGO_RSA_KEYSIZE`. 

This would involve adding code [here](https://github.com/jetstack/kube-lego/blob/de058f978f4c5106063ebd2af2f160abd5d2a377/pkg/kubelego/kubelego.go#L213) to receive a variable, and if one not set, utilize the constant value. Then a change would be made in [this](https://github.com/jetstack/kube-lego/blob/master/pkg/acme/user.go#L127) function to utilize the new variable for this value, instead of just consuming the constant.

**Comment by justjanne** [comment]
Please add this!

**Comment by munnerz** [comment]
Thanks for the thorough report @InAnimaTe - I've added the help-wanted label to this and assigned it to the next release. I'm currently trying to work through the back-log of issues and PRs, so won't have a chance to work on this myself just yet but contributions are very welcome, and I promise I'll get onto a review ASAP if there is one!
