### ISSUE TITLE
Certificate not get updated after add new domain to ingress tls spec [GCE]

### ISSUE THREAD

**Issue by zhangmengying** [jetstack/kube-lego#113]
At first, there's only one domain configured, and everything works fine.
spec:
  tls:
  - hosts:
    - first.mydomain.com
    secretName: "first.mydomain.com"

Later I add two more domain:
spec:
  tls:
  - hosts:
    - first.mydomain.com
    secretName: "first.mydomain.com"
- hosts:
    - second.mydomain.com
    secretName: "second.mydomain.com"
- hosts:
    - third.mydomain.com
    secretName: "third.mydomain.com"

After run the 'kubectl replace -f ingress.yaml' command. I can see the two new secret created, and new acme-challenge path added to the router. But the new https url doesn't work, I can see from the GCE console the frontend is still using the certificate only contains the first domain.

Environment:
kubernetes: 1.5.3
kube-loge: 0.1.3

**Comment by gianrubio** [comment]
@zhangmengying take a look on kube-lego and ingress logs. If you cannot figured out, please paste the logs here.

**Comment by zhangmengying** [comment]
@gianrubio   1d		2m		857	{loadbalancer-controller }			Warning		GCE	googleapi: Error 409: The resource 'projects/xxxxxxxx/global/sslCertificates/k8s-ssl-1-default-xxxxxx-ingress--46f47f09fa8dfc68' already exists, alreadyExists

**Comment by gianrubio** [comment]
Please run kube-lego with LEGO_LOG_LEVEL=debug to collect more info

**Comment by zhangmengying** [comment]
time="2017-03-24T03:38:05Z" level=debug msg="UPDATE ingress/default/knocknock-ingress" context=kubelego 
time="2017-03-24T03:38:05Z" level=debug msg="worker: begin processing true" context=kubelego 
time="2017-03-24T03:38:05Z" level=debug msg=reset context=provider provider=nginx 
time="2017-03-24T03:38:05Z" level=debug msg=finialize context=provider provider=nginx 
time="2017-03-24T03:38:05Z" level=info msg="disable provider no TLS hosts found" context=provider provider=nginx 
time="2017-03-24T03:38:05Z" level=debug msg=reset context=provider provider=gce 
time="2017-03-24T03:38:05Z" level=debug msg="UPDATE ingress/default/knocknock-ingress" context=kubelego 
time="2017-03-24T03:38:05Z" level=debug msg=finialize context=provider provider=gce 
time="2017-03-24T03:38:05Z" level=debug msg="setting up svc endpoint" context=provider namespace=default pod_ip="10.60.1.29" provider=gce 
time="2017-03-24T03:38:05Z" level=info msg="process certificates requests for ingresses" context=kubelego 
time="2017-03-24T03:38:05Z" level=info msg="creating new secret" context=secret name=knocknock.com namespace=default 
time="2017-03-24T03:38:05Z" level=info msg="no cert associated with ingress" context="ingress_tls" name=knocknock-ingress namespace=default 
time="2017-03-24T03:38:05Z" level=info msg="requesting certificate for first.knocknockapp.com,second.knocknockapp.com,third.knocknock.xyz" context="ingress_tls" name=knocknock-ingress namespace=default 
time="2017-03-24T03:38:06Z" level=debug msg="testing reachablity of http://third.knocknock.xyz/.well-known/acme-challenge/_selftest" context=acme domain=third.knocknock.xyz 
time="2017-03-24T03:38:06Z" level=debug msg="testing reachablity of http://second.knocknockapp.com/.well-known/acme-challenge/_selftest" context=acme domain=second.knocknockapp.com 
time="2017-03-24T03:38:06Z" level=debug msg="testing reachablity of http://first.knocknockapp.com/.well-known/acme-challenge/_selftest" context=acme domain=first.knocknockapp.com 
time="2017-03-24T03:38:07Z" level=debug msg="got authorization: &{URI:https://acme-v01.api.letsencrypt.org/acme/challenge/jPihTJed1sM6dvuwKQSIlz63RtSQmjZbDY8MJi1HH7o/846056963 Status:valid Identifier:{Type: Value:} Challenges:[] Combinations:[]}" context=acme domain=first.knocknockapp.com 
time="2017-03-24T03:38:07Z" level=info msg="authorization successful" context=acme domain=first.knocknockapp.com 
time="2017-03-24T03:38:07Z" level=debug msg="got authorization: &{URI:https://acme-v01.api.letsencrypt.org/acme/challenge/s5rHRsu6QAnu4pHy1PKHEL_GRnbcuRWjnqS8Cmzub9E/846057094 Status:valid Identifier:{Type: Value:} Challenges:[] Combinations:[]}" context=acme domain=second.knocknockapp.com 
time="2017-03-24T03:38:07Z" level=info msg="authorization successful" context=acme domain=second.knocknockapp.com 
time="2017-03-24T03:38:08Z" level=debug msg="got authorization: &{URI:https://acme-v01.api.letsencrypt.org/acme/challenge/Jk8cvWZavlETQ9XAProMxABZUtqEOycr1AI5mATOyuQ/845198112 Status:valid Identifier:{Type: Value:} Challenges:[] Combinations:[]}" context=acme domain=third.knocknock.xyz 
time="2017-03-24T03:38:08Z" level=info msg="authorization successful" context=acme domain=third.knocknock.xyz 
time="2017-03-24T03:38:09Z" level=info msg="successfully got certificate: domains=[first.knocknockapp.com second.knocknockapp.com third.knocknock.xyz] url=https://acme-v01.api.letsencrypt.org/acme/cert/037f90bac47dbad265f758e498760a8018e7" context=acme 
time="2017-03-24T03:38:09Z" level=debug msg="certificate pem data:\n-----BEGIN CERTIFICATE-----XXXXXXXXXXXXXXXXXXXXXXXX-----END CERTIFICATE-----\n" context=acme 
time="2017-03-24T03:38:09Z" level=info msg="creating new secret" context=secret name=knocknock.com namespace=default 
time="2017-03-24T03:38:09Z" level=debug msg="worker: done processing true" context=kubelego 
time="2017-03-24T03:38:09Z" level=debug msg="worker: begin processing true" context=kubelego 
time="2017-03-24T03:38:09Z" level=debug msg=reset context=provider provider=gce 
time="2017-03-24T03:38:09Z" level=debug msg=finialize context=provider provider=gce 
time="2017-03-24T03:38:09Z" level=debug msg="setting up svc endpoint" context=provider namespace=default pod_ip="10.60.1.29" provider=gce 
time="2017-03-24T03:38:09Z" level=debug msg=reset context=provider provider=nginx 
time="2017-03-24T03:38:09Z" level=debug msg=finialize context=provider provider=nginx 
time="2017-03-24T03:38:09Z" level=info msg="disable provider no TLS hosts found" context=provider provider=nginx 
time="2017-03-24T03:38:09Z" level=info msg="process certificates requests for ingresses" context=kubelego 
time="2017-03-24T03:38:09Z" level=info msg="cert expires in 90.0 days, no renewal needed" context="ingress_tls" expire_time=2017-06-22 02:38:00 +0000 UTC name=knocknock-ingress namespace=default 
time="2017-03-24T03:38:09Z" level=info msg="no cert request needed" context="ingress_tls" name=knocknock-ingress namespace=default 
time="2017-03-24T03:38:09Z" level=debug msg="worker: done processing true" context=kubelego 
time="2017-03-24T03:38:29Z" level=debug msg="UPDATE ingress/default/knocknock-ingress" context=kubelego 
time="2017-03-24T03:38:29Z" level=debug msg="worker: begin processing true" context=kubelego 
time="2017-03-24T03:38:29Z" level=debug msg=reset context=provider provider=nginx 
time="2017-03-24T03:38:29Z" level=debug msg=finialize context=provider provider=nginx 
time="2017-03-24T03:38:29Z" level=info msg="disable provider no TLS hosts found" context=provider provider=nginx 
time="2017-03-24T03:38:29Z" level=debug msg=reset context=provider provider=gce 
time="2017-03-24T03:38:29Z" level=debug msg=finialize context=provider provider=gce 
time="2017-03-24T03:38:29Z" level=debug msg="setting up svc endpoint" context=provider namespace=default pod_ip="10.60.1.29" provider=gce 
time="2017-03-24T03:38:29Z" level=info msg="process certificates requests for ingresses" context=kubelego 
time="2017-03-24T03:38:29Z" level=info msg="cert expires in 90.0 days, no renewal needed" context="ingress_tls" expire_time=2017-06-22 02:38:00 +0000 UTC name=knocknock-ingress namespace=default 
time="2017-03-24T03:38:29Z" level=info msg="no cert request needed" context="ingress_tls" name=knocknock-ingress namespace=default 
time="2017-03-24T03:38:29Z" level=debug msg="worker: done processing true" context=kubelego

Seems the new certificate is successfully created with all domain listed in the new ingress tls spec changes. But where is the newly created certificate? I can't find it in the google GCE console, and the fontend is still using the old certificate (which contains only one domain) after all.

**Comment by zhangmengying** [comment]
@gianrubio Hi there, today I suddenly found out it just started to works by itself, I hadn't done anything...
