### ISSUE TITLE
Support for adding CSR details via annotations?

### ISSUE THREAD

**Issue by HorizonXP** [jetstack/kube-lego#133]
Great project! Super simple to set up, which I think is awesome for all of us.

It would be great if we could provide identification information about the ownership of the domains via annotations, configmaps, or as a last case. I can see that at this line: https://github.com/jetstack/kube-lego/blob/master/pkg/acme/cert_request.go#L184, you're putting in the domain as the CommonName. This would probably be the right spot to put in additional information, like the organization, etc. But I don't know enough Go or about the project to figure out the best way to do that.

Is this something that can be put on the roadmap?

Thanks!

**Comment by nakato** [comment]
It's my understanding that LetsEncrypt does not support setting these values, as the automatic validation can not automatically validate these values are truthful.

Can you find in the LE documentation that setting these values is supported?

**Comment by HorizonXP** [comment]
Well, I'm a dummy. Clearly that would be something that Let's Encrypt doesn't support, since it cannot be automatically validated. Closing the issue, and leaving these comments for everyone to see, for all of eternity!
