### ISSUE TITLE
Node upgrades

### ISSUE THREAD

**Issue by johnparn** [jetstack/kube-lego#145]
Hi!

Thanks for this splendid tool, good work!

I'm about to update my cluster, but before doing so I would just like hear if I should take any precautions when it comes to kube-lego?

At the moment the nginx-ingress is running as two pods with a static IP associated with it. All in all I have about 50 certificates installed, bundled in about 5 SAN certs. When doing the upgrade, do I have to take care to copy the secrets and/or do the move of service/deployments in a specific order?

**Comment by munnerz** [comment]
Hey @johnparn,

So kube-lego itself only stores data in the Kubernetes API server. Whilst I can't comment on your specific use-case without seeing your current k8s deployment and your planned upgrade strategy, provided you properly upgrade Kubernetes and retain the contents of etcd, there should be no issues.

There's a list of actions required when upgrading Kubernetes here: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#action-required - none of them specifically effect kube-lego, but some do affect Kubernetes as a whole (eg. the migration from etcd2 to etcd3).

How are you planning on upgrading your cluster?

**Comment by johnparn** [comment]
@munnerz Thanks for your swift answer!

The setup is quite simple and straightforward with 5 namespaces - kube-system, kube-lego, nginx-ingress, production and staging. Production and staging houses 7 stateless web services, all using REST API:s for handling data, so there is no data storage available at GKE which may make it a bit easier. 

I was thinking of upgrading the nodes using the web interface, see picture below:

<img width="472" alt="node-update" src="https://cloud.githubusercontent.com/assets/1776929/24909285/96d3ff2a-1ec3-11e7-9043-2e8f440d2065.png">

My main concern is when a node upgrade is preformed each node is replaced and I just want to make sure that no new certs are issued during the process, that the old secrets and certs can be reused. I've been burnt before when I hit a limit of the number of certs that may be issued per week.

**Comment by munnerz** [comment]
Ah, if you are hosted on GKE you should be fine!

The master is what stores all the kube-lego data. If the node that is running kube-lego is shutdown half way through requesting a certificate, it will simply be retried again once kube-lego comes back up. All your existing secrets & ingress definitions will still be compatible 😄

**Comment by johnparn** [comment]
Ok, fine. I was worried that the order of the deployments being moved/replaced would trigger reissue of new certs as the ingresses of the deployments are upgraded.

**Comment by munnerz** [comment]
What do you mean by moved/replaced here? If you're just clicking the Upgrade button in GKE, the resources won't be moved to a new cluster *or* replaced. The master component is what stores the manifests, so there's no movement or replacement happening in the background :)

In case you haven't seen already, the GKE docs explain some of the detail of cluster upgrades: https://cloud.google.com/container-engine/docs/clusters/upgrade

**Comment by johnparn** [comment]
I read this and got the impression when a new version created it will replace the current running node

https://cloud.google.com/container-engine/docs/clusters/upgrade#the_node_upgrade_flow

**Comment by simonswine** [comment]
I think this can be closed? If not feel free to re-open
