### ISSUE TITLE
tectonic ingress class

### ISSUE THREAD

**Issue by kersten** [jetstack/kube-lego#154]
Hi,

I got everything now up and running in my tectonic cluster, but after adding ```kubernetes.io/tls-acme: "true"``` kube-lego ignores the ingress with message:

```ignoring as unsupported ingress class 'tectonic'" context=ingress name=example.domain.tld namespace=websites```

Tectonic ingress uses nginx as LB would someone help me getting this fixed?

**Comment by gianrubio** [comment]
@kersten  change the [env vars]( https://github.com/jetstack/kube-lego#environment-variables ) `LEGO_SUPPORTED_INGRESS_CLASS` and `LEGO_DEFAULT_INGRESS_CLASS`  to `tectonic`

**Comment by kersten** [comment]
@gianrubio then I get ```Unsupported default ingress class: 'tectonic'```

If I only set ```LEGO_SUPPORTED_INGRESS_CLASS ``` to ```tectonic``` I get the same error again.

**Comment by kersten** [comment]
OK, using canary version works now!

**Comment by coresolve** [comment]
I am working through this as well. @kersten what do you mean by canary version?

**Comment by coresolve** [comment]
@kersten @gianrubio 
When I setup kube-lego using the canary image. I am able to set:
`LEGO_SUPPORTED_INGRESS_CLASS` to `tectonic`
When I set
`LEGO_DEFAULT_INGRESS_CLASS` to `tectonic` I get the same error:
```
time="2017-05-28T18:06:14Z" level=info msg="successfully connected to kubernetes api v1.6.2+coreos.0" context=kubelego
time="2017-05-28T18:06:14Z" level=info msg="server listening on http://:8080/" context=acme
time="2017-05-28T18:14:29Z" level=info msg="ignoring as unsupported ingress class 'tectonic'. Did you you forget to specify LEGO_DEFAULT_INGRESS_CLASS ?" context=ingress name=simplewebapp-ingress namespace=dcooley-demo
```
Not sure how this worked before. 

Here is a description of the pod. 
```
$ kubectl describe rs tectonic-lego-kube-lego-3364267746 --namespace=kube-system
Name:		tectonic-lego-kube-lego-3364267746
Namespace:	kube-system
Selector:	app=kube-lego,pod-template-hash=3364267746,release=tectonic-lego
Labels:		app=kube-lego
		pod-template-hash=3364267746
		release=tectonic-lego
Annotations:	deployment.kubernetes.io/desired-replicas=1
		deployment.kubernetes.io/max-replicas=2
		deployment.kubernetes.io/revision=2
Replicas:	1 current / 1 desired
Pods Status:	1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:	app=kube-lego
		pod-template-hash=3364267746
		release=tectonic-lego
  Containers:
   kube-lego:
    Image:	jetstack/kube-lego:canary
    Port:	8080/TCP
    Requests:
      cpu:	20m
      memory:	8Mi
    Readiness:	http-get http://:8080/healthz delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:
      LEGO_NAMESPACE:			 (v1:metadata.namespace)
      LEGO_POD_IP:			 (v1:status.podIP)
      LEGO_EMAIL:			dcooley@coreos.com
      LEGO_PORT:			8080
      LEGO_URL:				https://acme-staging.api.letsencrypt.org/directory
      LEGO_DEFAULT_INGRESS_CLASS:	tectonic
      LEGO_SUPPORTED_INGRESS_CLASS:	tectonic
```

**Comment by adarshaj** [comment]
bump!

I still see the same error as reported by @coresolve on jestack/kube-lego:canary, any workarounds?
/cc @gianrubio

**Comment by coresolve** [comment]
I got this working here: 

git.io/coresolve-ingess

**Comment by adarshaj** [comment]
Thank you @coresolve it worked! 

there's a typo in the link though, 'g' was missing. For those discovering this later - go to https://git.io/coresolve-ingress
