### ISSUE TITLE
New ingress rules for `kube-lego-nginx` are not added

### ISSUE THREAD

**Issue by tim-smart** [jetstack/kube-lego#17]
When I create more than one ingress resource with tls host entries, they aren't added to the rules of the kube-lego ingress config.

I have to manually add the hosts to make sure the `/.well-known/...` is proxied to the kube-lego service.

**Comment by simonswine** [comment]
Ok, I had a similar experience lately. I will investigate later. Right now test coverage is not really good. Probably downgrade to 0.0.4 meanwhile...

I will have a look as soon as I have a chance...

**Comment by simonswine** [comment]
@tim-smart It would great if you could provide me with a gist of:
`kubectl get ingress --all-namespaces -o ymal`

**Comment by tim-smart** [comment]
I'll spin up a cluster in the next couple hours and reproduce the issue.

**Comment by tim-smart** [comment]
https://gist.github.com/tim-smart/6cda9c94a56d2ff5c598c07822710bfe

**Comment by simonswine** [comment]
I think the problem was that ingress object updates failed. Could you test if this image: `jetstack/kube-lego:canary` solves your problems.

8592269b1dc5a07696aec81db4445de7bdb11ff9

**Comment by tim-smart** [comment]
Yes that fixes it! Thanks
