### ISSUE TITLE
Test Certificate Renew

### ISSUE THREAD

**Issue by chainlink** [jetstack/kube-lego#180]
Hi there,
Is there a way to trigger a renew to test that the certificate renews correctly?

**Comment by gianrubio** [comment]
Yes, you can do it:

1- Comment [this lines](https://github.com/jetstack/kube-lego/blob/master/pkg/kubelego/kubelego.go#L312-L314)

2-Build a new release running `$ make docker DOCKER_IMAGE=gianrubio/kube-lego`

3-Start lego with LEGO_MINIMUM_VALIDITY=1h

Be warned that letsencrypt can throttle you if you do this too often.

**Comment by chainlink** [comment]
Thanks!
