### ISSUE TITLE
Timed out from Let's Encrypt made kube-lego crash

### ISSUE THREAD

**Issue by pichouk** [jetstack/kube-lego#185]
I just noticed that my kube-lego container crash a lot. I have this log line just when it crash :
```
time="2017-05-19T09:45:40Z" level=fatal msg="fatal error verifying existing user: failed to retrieve ACME account for URI 'https://acme-v01.api.letsencrypt.org/acme/reg/8656258': 504 : 504 Gateway Time-out" context=acme 
```
It happens just after it try a certificate request for a domain which not (yet) point to my server. I don't know if :
- it fails because of a Let's Encrypt side issue (HTTP 504)
- it fails because my domain is not pointing to my server

In any case, I think it is a problem that the container crash if it run into an HTTP504.

**Comment by c-n-d** [comment]
To the first point, it is likely related to the recent [Let's Encrypt outage](https://news.ycombinator.com/item?id=14374933) (although your domain should be pointing to a web server before requesting a certificate).

In the short term, the workaround that resolved the 504s for me was deleting the `kube-lego-nginx` secret and redeploying `kube-lego` to the cluster.

**Comment by pichouk** [comment]
Yes my configuration was not good on this example, I was just reporting because I think kube-lego should not crash when Let's Encrypt return an HTTP 504. This is not a big issue, since Kubernetes restart the pod instantly, but still annoying. 
Can we imagine a behavior where it only skip this request ?

**Comment by fiws** [comment]
Why close the issue when it's still a problem?

Even if this repo is dead, i think closing something that is not fixed is not good.
