### ISSUE TITLE
Meeting to discuss potential move to kubernetes-incubator

### ISSUE THREAD

**Issue by munnerz** [jetstack/kube-lego#186]
So as to not exclude those not watching other repositories - we are holding a meeting on Wednesday (24th) at 3.30pm UTC to discuss potentially merging and moving this project and PalmStoneGames/kube-cert-manager into kubernetes-incubator.

For full context, the issue in question is here: https://github.com/PalmStoneGames/kube-cert-manager/issues/33

If you'd like to attend, please drop me an email at james [at] jetstack.io or make it known here. Thanks!

**Comment by pichouk** [comment]
Do you have anything new about this ? Will `kube-lego` be merge in another place ?
