### ISSUE TITLE
Error 503 when reaching /.well-known/acme-challenge

### ISSUE THREAD

**Issue by koalalorenzo** [jetstack/kube-lego#193]
Hello, 
I am trying to use `kube-lego` but I am running into a problem. According to the logs it returns a 503 error. I have read that this problem is usually caused by the namespaces, so I put both `nginx-ingress-controller` and `kube-lego` under `kube-system` where the rest of the ingresses are in `default`, but nothing changed.

You can read the manifests of both the ingress controller and `kube-lego` [here](https://ipfs.io/ipfs/QmS421VsgTSsPrmsummbAy9RKxdc7hDAv3s9nvuu385A5h).
I can manually validate that both HTTP and HTTPS requests to `$DOMAIN/.well-known/acme-challenge` are retiring a 503 error.

What could it be?

**Comment by pichouk** [comment]
Same issue here.
It worked perfectly until now, when my ingress controller (`nginx-ingress-controller`) and `kube-lego` where in the `default` namespace. I moved ingress and `kube-lego` to another namespace, and now I got the same issue. I tried with `kube-lego` versions `0.1.4` and `0.1.3`, same thing.

When `kube-lego` try to renew/request a certificate, it log this (`debug` log level)
```
time="2017-05-31T08:00:19Z" level=debug msg="testing reachablity of http://www.domain.tld.well-known/acme-challenge/_selftest" context=acme domain=www.domain.tld 
time="2017-05-31T08:00:19Z" level=debug msg="error while authorizing: reachabily test failed: wrong status code '503'" context=acme domain=www.domain.tld 
```

I got this on my ingress controller logs :
```
 - [162.27.127.12, 127.0.0.1] - 52788 -  - - [31/May/2017:07:59:04 +0000] "GET /.well-known/acme-challenge/_selftest HTTP/1.1" 503 214 "-" "Go-http-client/1.1" 318 0.000 [-] - - - -
162.27.127.12 - [162.27.127.12] - 56374 - 56374 - - [31/May/2017:07:59:04 +0000] "GET /.well-known/acme-challenge/_selftest HTTP/1.1" 503 214 "-" "Go-http-client/1.1" 143 0.001 [default-kube-lego-nginx-8080] 127.0.0.1:8181 214 0.001 503
``` 

It seems that the `kube-lego` backend for `.well-know` is not working, returning HTTP 503.

**Comment by pichouk** [comment]
Ok, just solved it.
Actually I got 2 `kube-lego-nginx` ingress rules for `.weel-know/acme-challenge` : one on the current `kube-lego` namespace (`infra` for me) and another (the old one) on the `default` namespace. I just delete the old one and it works.

@koalalorenzo Not sure if it is the same for you, but try to run :
`kubectl get --all-namespaces ing | grep kube-lego` and delete all `kube-lego-nginx` ingress rules which are not in the same namespace as your current `kube-lego` pod.
If not working, can you share your `kube-lego` and ingress controller logs ?

**Comment by koalalorenzo** [comment]
So, the way to solve this for me was to deploy `kube-lego` in its own namespace. But I think that this should still be marked as bug, as probably there is something that tight and strictly links `kube-lego` to its own namespace.

The logs were the same (very similar) to the one that you have!

**Comment by pichouk** [comment]
I don't really know how exactly `kube-lego` works internally, but on my side I was able to made `kube-lego` works and I have the following organisation :
- `kube-lego` running in a namespace `infra`
- some other stuff (like my `nginx-ingress-controller`) also running in namespace `infra`
- some other stuff on a lot of various namespaces
So I think it is possible to made everything works without a dedicated namespace for `kube-lego`.
I am running on kubernetes `1.5.6`.

**Comment by p-pawlak** [comment]
Had the same problem on` 1.6.2`. The config generated by `nginx-ingress-controller` listed `127.0.0.1:8181` as the upstream. Running
`kubectl expose deployment kube-lego --port=8080 --name=kube-lego-nginx`
fixed that. No separate namespace was necessary, in fact deploying `kube-lego` in its own namespace messed with my fine-tuned RBAC rules.

**Comment by koalalorenzo** [comment]
The latest version actually seems tho have this fixed! Thank you so much for your help! In case it will change I will re open the task!
