### ISSUE TITLE
[GCE] Can we force https ?

### ISSUE THREAD

**Issue by adrienbarreau** [jetstack/kube-lego#200]
Is there any way to force https ? By redirecting http requests to https ?

**Comment by madziefe** [comment]
```
ingress.kubernetes.io/force-ssl-redirect: 'true' 
or
ingress.kubernetes.io/secure-backends: 'true'
```
https://github.com/kubernetes/ingress/blob/master/docs/annotations.md

**Comment by adrienbarreau** [comment]
ingress.kubernetes.io/force-ssl-redirect and ingress.kubernetes.io/secure-backends appears to be for nginx and trafficserver. Not GCE.

**Comment by hut8** [comment]
Unfortunately that seems to be the case, @adrienbarreau . I agree that GCE should support this but apparently it doesn't. Also, it seems as though this doesn't really have anything to do with this project, but should be filed in  the GCE Ingress repo (although I'm sure it already has)

**Comment by thecodeassassin** [comment]
Yeah this is also really important for us. RIght now we force on the application side of things but there should be a better solution.

**Comment by adrienbarreau** [comment]
How can you force on the application side @thecodeassassin  ? From my application perspective protocol is always http as the load balancer send http requests to my application. Therefore I can't check if it's http or https to do a redirection.

**Comment by thecodeassassin** [comment]
@adrienbarreau  we use the X-Forwarded-Proto header to determine if the user used http or https.

**Comment by munnerz** [comment]
I'm going to close this as it's not an issue relating directly to kube-lego 😄
