### ISSUE TITLE
Example GCP, where is the secret name referenced? 

### ISSUE THREAD

**Issue by chrissound** [jetstack/kube-lego#246]
https://github.com/jetstack/kube-lego/blob/6b5cb1375c44d7a98feea9eef96b8dda4a8fd65d/examples/gce/echoserver/ingress-tls.yaml#L13

How is the 'secret' referenced on the certificate generation side of things? Can I change this value or is it hardcoded?

**Comment by ankon** [comment]
kube-lego will search for an existing secret with that name (and specific content, see the ingress documentation), and if it doesn't exist (or is outdated, IIRC) will use letsencrypt to create a new certificate and store it in that secret. Therefore: yes, you can pick any valid name for this value.

**Comment by chrissound** [comment]
Thank you!
