### ISSUE TITLE
Document how to switch from staging to prod LE server

### ISSUE THREAD

**Issue by munnerz** [jetstack/kube-lego#248]
Re: @lukemarsden's tweet (https://twitter.com/lmarsden/status/902481626273329153)

We should clearly document how to switch from letsencrypt staging/prod in the README to save extra issues/confusion!

**Comment by lukemarsden** [comment]
To be fair, this is already [documented here](https://github.com/jetstack/kube-lego#usage), but maybe this process could have its own heading, with sample `kubectl` commands to make it more explicit?

**Comment by lukemarsden** [comment]
P.S. Thank you for developing `kube-lego`, it's great!

**Comment by CheshireSwift** [comment]
I think just putting a heading or something in bold around that existing documentation would go a long way.

I had this exact issue, resolved it myself, came to check it wasn't mentioned in the docs, missed it when skimming and then found this issue... That's a very circuitous route to find the docs for such a common thing!

**Comment by sfrique** [comment]
I do like the #294 idea!
