### ISSUE TITLE
Is there anyone looking after this project?

### ISSUE THREAD

**Issue by thekalinga** [jetstack/kube-lego#251]
Its been more than 45 days since a [pull request to support haproxy](https://github.com/jetstack/kube-lego/pull/228) is sent for this repo.

HAProxy is a widely used reverse proxy. Not a single comment/review is posted by the maintainers of the repo towards the pull request.

Are there active maintainers on this project? If so, is it possible for your to provide comments/accept the pull request?

CC: @jcmoraisjr @jetstack

**Comment by munnerz** [comment]
Hi there,

Yep, we are active on the project, however have quite a lot of operational burden as it is. We're actively working on a replacement to kube-lego, that does not couple us to particular ingress controllers, as well as a wide range of other features, over in the github.com/jetstack-experimental/cert-manager repo. As a result, we've:

1) Had less time to deal with PRs/issues on kube-lego
2) Been less inclined to accept feature PRs into this repository, as it will require us support these features on-going alongside cert-manager.

I'm sorry your PR has gone unattended/unnoticed for a while now - I'll spend some time this morning looking over it, and leave comments over there.

If you're interested, please take a look at cert-manager and I'm very keen to hear your experience with other ingress controllers.

**Comment by thekalinga** [comment]
@munnerz Thanks for the prompt response.
