### ISSUE TITLE
Kubernetes 1.8 completely deprecates Third Party Resources - CRD's are the new TPR

### ISSUE THREAD

**Issue by ds0nt** [jetstack/kube-lego#261]
CRD is the successor to the deprecated ThirdPartyResource (TPR) API, and is available as of Kubernetes 1.7.

https://kubernetes.io/docs/tasks/access-kubernetes-api/migrate-third-party-resource/

**Comment by christiannaths** [comment]
Ha! Had the same reaction. Headed here and https://github.com/kelseyhightower/kube-cert-manager straight away

**Comment by ds0nt** [comment]
My mistake `certificate.stable.k8s.psg.io` is from `https://github.com/PalmStoneGames/kube-cert-manager/blob/master/docs/create-a-certificate.md`.
