### ISSUE TITLE
Stuck creating ingress

### ISSUE THREAD

**Issue by Coolfeather2** [jetstack/kube-lego#262]
![image](https://user-images.githubusercontent.com/14107982/31578633-af7a7672-b157-11e7-9b54-510b74634715.png)
Because the ingress isn't being made the kube-lego pod is stuck testing reachability of http://subdomain.domain.net/.well-known/acme-challenge/_selftest

**Comment by Coolfeather2** [comment]
kube-lego was creating a nginx ingress instead of gce - fixed

**Comment by Noah-Huppert** [comment]
How did you direct kube-lego to create a GCE controller? I am experiencing the same issue right now.

**Comment by Coolfeather2** [comment]
Do you have:
```
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
```

**Comment by Noah-Huppert** [comment]
I did not have the `kubernetes.io/ingress.class: "gce"` annotation. Thank you.
