### ISSUE TITLE
Reachability test failed: no such host. But host is available

### ISSUE THREAD

**Issue by arrowcircle** [jetstack/kube-lego#278]
Hello! I am trying to setup kube-lego for my minio server.
After applying tls configuration for it, I see this messages in log of kube-lego:

```
time="2017-11-16T10:55:10Z" level=debug msg="testing reachability of http://s3.kubernetes.mydomain.com/.well-known/acme-challenge/_selftest" context=acme domain=s3.kubernetes.mydomain.com
time="2017-11-16T10:55:10Z" level=debug msg="error while authorizing: reachability test failed: Get http://s3.kubernetes.mydomain.com/.well-known/acme-challenge/_selftest: dial tcp: lookup s3.kubernetes.mydomain.com on 10.233.0.3:53: no such host" context=acme domain=s3.kubernetes.mydomain.com
```
But if I try to curl it from master or another host, I get proper response.

```
curl http://s3.kubernetes.mydomain.com/.well-known/acme-challenge/_selftest
UtvITnmTxXWbIrGc
```
Without certs, service is accessible an works fine.

Where I need to dig to solve this problem?

**Comment by mcwienczek** [comment]
I am having  the same problem. If you closed the issue, could you explain whether you did solve the issue and how?

**Comment by inyee786** [comment]
@arrowcircle how you solved the above problem??
