### ISSUE TITLE
May be a bug?

### ISSUE THREAD

**Issue by decker502** [jetstack/kube-lego#28]
Should code be below　in tls.go?

```
	if !i.newCertNeeded(i.ingress.kubelego.LegoMinimumValidity()) {
		i.Log().Infof("no cert request needed")
		return nil
	}
```

**Comment by simonswine** [comment]
Not really getting what the problem is here. Could you elaborate a bit more on that?

**Comment by decker502** [comment]
The parameter of the function `newCertNeeded(minimumValidity time.Duration)`  is mininumvalidity, but the caller's is
```    
  if !i.newCertNeeded(i.ingress.kubelego.LegoCheckInterval()) {
		i.Log().Infof("no cert request needed")
		return nil
	}
```

I think it should be 
```
    if !i.newCertNeeded(i.ingress.kubelego.LegoMinimumValidity()) {
        i.Log().Infof("no cert request needed")
        return nil
    }
```

**Comment by simonswine** [comment]
@decker502 thanks for reporting this, was definitely a bug and I was a bit blind to see the problem! Should be fixed in the latest canary image build `jetstack/kube-lego:canary`
