### ISSUE TITLE
[feature-request] Issue Cert for www with nginx-ingress "from-to-www-redirect" annotation

### ISSUE THREAD

**Issue by boyander** [jetstack/kube-lego#292]
Since version 0.9.0 you can add the following annotation to an nginx-ingress controller
```
annotations:
    ingress.kubernetes.io/from-to-www-redirect: "true"
```
It is possible to add www as a subdomain for the requested cert when this annotation is present?

**Comment by noamackerman** [comment]
+1

**Comment by boyander** [comment]
I'm closing the issue, not sure if actually implemented, but managed to do it by adding another host or ingress record to k8s.
