### ISSUE TITLE
Which IP do I point my domain at?

### ISSUE THREAD

**Issue by devth** [jetstack/kube-lego#3]
In the screencast example, it shows two ingress resources: `echoserver` and `kube-lego`. Each one has 2 external IP addresses. Which one do you use for the `demo.kube-lego.jetstack.net` A record?

It'd be helpful to include this in the docs.

**Comment by dylangrafmyre** [comment]
The External IP listed under the `echoserver` `kubectl service` is what gets used for the A record.

**Comment by simonswine** [comment]
I think this depends on the environment you are running your cluster in.

In general you want to expose only the ports 80/443 of the `nginx` pods. This is done by the `nginx` service with the type `LoadBalancer`. The ingress information is misleading as it contains only the public addresses of the nodes, that run the nginx pods.

You can get the right IPs/hostnames with `kubectl describe svc nginx`.

For AWS the service creates an ELB and you should point the domain to the `Hostname` via CNAME.
The hostname should look like that: `<name>.eu-west-1.elb.amazonaws.com`

For AWS the service creates an Forwarding Rule and you can create an a record to the `LoadBalancer Ingress` in the `describe` output.

Gonna add this to the example docs later

**Comment by devth** [comment]
Got it, thanks. Is it ok to increase the nginx deployment replica count or would they conflict? Since nginx is proxying all traffic I'd like to have more than one running in case of failure.

**Comment by simonswine** [comment]
Yeah sure for a production-like use case you want to have more replicas. There is not really a conflict. 

The only problem is around TLS Session caching and ticketing. As the nginx instances don't share the cache nor the secrets for ticketing, session resumption is is not working and the TLS has to re-initialised every time it hits another nginx instance.

**Comment by devth** [comment]
Would it make sense to write cache to a dir and read it on startup? That way we could use persistent volumes to share cache among replicas.

**Comment by simonswine** [comment]
One way could be to generate a key for tickets and disable session cache: http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_session_ticket_key
(This key has to be rotated quite regularly.)

To share the session cache you have to modify nginx. (`ssl_session_cache` has to support something like redis/memcache) (I think there is something like `ssl_session_store_by_lua` on openresty's road map)

**Comment by simonswine** [comment]
I am now at least mentioning how to find out about the IP address/hostname

https://github.com/jetstack/kube-lego/commit/422b42bfbc17ea43e1debfd80baf256bc2247831
