### ISSUE TITLE
The tls-sni challenge has been disabled due to strong credibility of a vulnerability report

### ISSUE THREAD

**Issue by jozuenoon** [jetstack/kube-lego#302]
I'm carious how this issue affect kube-lego:
https://news.ycombinator.com/item?id=16112237
https://letsencrypt.status.io/pages/incident/55957a99e800baa4470002da/5a55777ed9a9c1024c00b241

**Comment by knsakib** [comment]
It affects kube-lego. It is not working anymore!

**Comment by anp** [comment]
Looks like it's using HTTP challenges? https://github.com/jetstack/kube-lego/blob/master/pkg/acme/acme.go#L77-L128

**Comment by irontoby** [comment]
kube-lego does indeed use http-01 validation, not tls-sni validation, and so it is not affected by the issue.

See: https://blog.jetstack.io/blog/kube-lego/

"Currently, the only implemented validation method is Simple HTTP".

**Comment by jozuenoon** [comment]
Thanks for comments!
