### ISSUE TITLE
Wildcard Certificate Support

### ISSUE THREAD

**Issue by lucasilverentand** [jetstack/kube-lego#304]
With the arrival of wildcard certificates on the 27th of February I would like to suggest adding support for this feature to kube-lego. It would require the addition of the new ACME v2 api and the DNS-01 verification process. I think this would be great for setups with CI that publish review apps under subdomains automatically. Please let me know you guys' thoughts on this matter.

**Comment by simonswine** [comment]
There are no plans to implement that

>  kube-lego is in maintenance mode only. There is no plan to support any new
>  features. The latest Kubernetes release that kube-lego officially supports
>  is **1.8**.  The officially endorsed successor is **[cert-manager](https://github.com/jetstack/cert-manager/)**.
>
>  If you are a current user of kube-lego, you can find a migration guide [here](https://github.com/jetstack/cert-manager/blob/master/docs/user-guides/migrating-from-kube-lego.md).

**Comment by georgecrawford** [comment]
@simonswine I believe the working documentation link is http://docs.cert-manager.io/en/latest/tutorials/acme/migrating-from-kube-lego.html.
