### ISSUE TITLE
Duplicate secret causes exhaustion of duplicate certificates for same name

### ISSUE THREAD

**Issue by chaosaffe** [jetstack/kube-lego#31]
When a secret already exists with the the name configured in the TLS directive for ingress a duplicate or replacement secret cannot be created (error `Invalid value: \"kubernetes.io/tls\": field is immutable"`).

As a result, kube-lego repeatedly requests a cert for the same subdomain, meaning you only have a few seconds before hitting the [_Duplicate Certificate_ rate limit](https://letsencrypt.org/docs/rate-limits/)

```
time="2016-09-16T15:14:58Z" level=debug msg="testing reachablity of http://sub.example.com/.well-known/acme-challenge/_selftest" context=acme host=sub.example.com
time="2016-09-16T15:14:58Z" level=info msg="initialize lego acme connection" context=acme
2016/09/16 15:14:58 [INFO][sub.example.com] acme: Obtaining bundled SAN certificate
2016/09/16 15:14:58 [INFO][sub.example.com] acme: Trying to solve HTTP-01
2016/09/16 15:14:58 [INFO][sub.example.com] The server validated our request
2016/09/16 15:14:58 [INFO][sub.example.com] acme: Validations succeeded; requesting certificates
time="2016-09-16T15:14:59Z" level=warning msg="Error while obtaining certificate: Errors while obtaining cert: map[sub.example.com:acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: Too many certificates already issued for exact set of domains: sub.example.com]" context=acme
```

This could be avoided in two ways:
1. Check if a secret with the same name exists _before_ attempting creation of a certificate
2. When a cert has been retrieved successfully, but then an error occurs either cache or drop the cert, log the error, but do not request the cert again. This would allow for the user to rectify the issue and then cert creation could be attempted again when the application is restarted.

**Comment by jsindy** [comment]
Hit this issue as well, it would be best to have the ability to use wildcard or add subdomains to the same cert.

**Comment by chaosaffe** [comment]
Lets Encrypt doesn't currently offer wildcard certificates. This isn't a limitation in Kube-Lego. 

Regarding adding multiple domains/subdomains in the same cert, this is possible. Just specify them in your ingress. There is documented.

**Comment by gmistick** [comment]
Just happend to me, already had a certificate and this caused kube-lego to exhaust the rate limit, now i'm stuck 4 days without a way to recreate certificate :(

**Comment by scruplelesswizard** [comment]
Stale, closing
