### ISSUE TITLE
Let's Encrypt Wildcard Support

### ISSUE THREAD

**Issue by jesseshieh** [jetstack/kube-lego#322]
First of all, thanks for building kube-lego! It's really great. 

Let's Encrypt is working on supporting [wildcard certificates](https://letsencrypt.org/2017/07/06/wildcard-certificates-coming-jan-2018.html). It's [not ready yet](https://community.letsencrypt.org/t/acmev2-and-wildcard-launch-delay/53654) so this issue is really more of a placeholder feature request, but I'm wondering whether or not kube-lego plans to support wildcard certificates once they are available. 

Thanks again!

**Comment by Palakis** [comment]
Update: starting from today (2018-03-13), Wildcard Support is live: https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

**Comment by tmaier** [comment]
I don't think so. See #318

**Comment by Palakis** [comment]
@tmaier Wilcard Support was staging-only until yesterday. It's now live on production.

**Comment by Palakis** [comment]
Anyway, it's still better to add this to cert-manager of course.

**Comment by StephanX** [comment]
letsencrypt's release note: https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

Would also love to start utilizing this.

**Comment by pvsousalima** [comment]
has anyone already tested with the new feature? or has it given support yet?

**Comment by pvsousalima** [comment]
Thanks for this amazing project! Has anyone already tested with the new feature? Or has started to give support yet? Thanks!

**Comment by Hagbarth** [comment]
If there is any need for contributions to make this happen, I'm more than willing to work on it.

**Comment by munnerz** [comment]
kube-lego will never support let's encrypt wildcard certificates, not least because they require DNS01 validation to obtain.

If you want to get wildcard certs, try out the v0.3.0-alpha.1 release of cert-manager. I'm going to close this issue now as I don't think it's actionable!

**Comment by justjanne** [comment]
@munnerz cert-manager is significantly more complex to set up, and in many configurations, and fails without any useful error messages where kube-lego works fine. The EOL of kube-lego is problematic under that light.
