### ISSUE TITLE
Ingress tls secrets only updated if delete+create is used (and not update)?

### ISSUE THREAD

**Issue by lestrrat** [jetstack/kube-lego#40]
(Warning: This report is a bit fuzzy)

I had kube-lego setup to update the certificates if they had 30 days or less to expire. Looking at the `kubectl logs` output, this was performed correctly on kube-lego side. It was reporting that the certificate it was seeing had 70 days to go, which matched the timestamp of the secret associated with it.

However, no matter how long I waited, the actual certificate as seen by my external checker was the old one, with 20 days left to go.

I started looking for clues, and I found https://code.google.com/p/google-cloud-platform/issues/detail?id=105
This suggests to use `kubectl replace --force -f secret.json`, so I did `kubectl get -o json secret my-certificate` and fed that backt o the `kubectl replace` command. at which point the certificate seemed to have been updated. So maybe GCE HTTP(s) Load Balancers require us to destroy the resource first and to re-create it, in order to force a reload? 

I'm not 100% sure if this was the correct symptom/fix yet, but at this moment I highly suspect that [this line here](https://github.com/jetstack/kube-lego/blob/master/pkg/secret/secret.go#L62) needs to be Delete+Create instead of update

![image](https://cloud.githubusercontent.com/assets/49281/19026790/f40a396a-8964-11e6-8e2e-547529eb7e4e.png)

Again, sorry about the fuzzy report, but I'm also trying to figure out what is going on here :/

**Comment by simonswine** [comment]
As far as I understand it the problem lies in the GCE ingress controller. I could implement a work around for GCE ingresses, but I guess it would be way better to fix the behaviour in the ingress controller. 

The clues I found are around this GCE ingress issue: https://github.com/kubernetes/contrib/issues/1396

Maybe we try to fix it there first...

**Comment by bprashanth** [comment]
I just tried this and it works as intended: https://github.com/kubernetes/contrib/issues/1396#issuecomment-255480373

What version of Kubernetes are you running?

**Comment by lestrrat** [comment]
@bprashanth This being 21 days ago... probably Kubernetes 1.3.7 (guessing from the [GKE release notes](https://cloud.google.com/container-engine/release-notes)), or possibly a version or two behind, such as 1.3.5 or 1.3.6. Pretty sure it was NOT 1.2.x, as I remember upgrading to 1.3.4 or 1.3.5 from 1.2.x, and then moved on to 1.3.7

After I filed this issue, my clusters are now on 1.4.0 (which, now looking at the above release-notes, sure looks like I'm already a few micro versions behind :), and I haven't needed to replace certs yet, so I haven't seen the problem again.

If you think this issue should be fixed in 1.4.0, please mark this as "confirmation required" or some such, and I can confirm in about 2 months, when my next certs expire... :D

**Comment by simonswine** [comment]
Just tried that on a GKE cluster created today with kube-lego `0.1.3` and it worked without an issue. 

Feel free to reopen if needed
