### ISSUE TITLE
New tag / release?

### ISSUE THREAD

**Issue by cgag** [jetstack/kube-lego#54]
From looking at the issues, it seems that 1.2 can fail to renew certs (or possibly always causes an 8 hour expiration?) because it was using CheckInterval instead of MinimalValidity.   I see that this is fixed in the canary tag, but that appears to be tracking master, and I don't want to depend on a mutable tag.

Any thoughts on cutting a new release with the fixed validity issue?

edit:  Though I suppose if you set checkinterval to 5 minutes[0], you shouldn't have more than 5 minutes of invalid certs.

[0]:  I think this minimum value is too high, the check seems like a lightweight thing, I don't think setting it to something outrageously low like 10 seconds would really cause problems, I may be wrong

edit: I found a couple of bugs that I have patches for on my fork, will submit prs soon

**Comment by simonswine** [comment]
I will cut a new release as soon I have tested the latest master against GLBC/nginx

**Comment by simonswine** [comment]
About the check interval: The checks will run periodically if nothing around your ingresses change. (This should only apply to expiring certificates. If you change one of your ingress objects the change should trigger a reevaluation of the certs right away...

**Comment by simonswine** [comment]
Ok 0.1.3 is released
