### ISSUE TITLE
Only adds one cert to load balancers on GCE

### ISSUE THREAD

**Issue by schurig** [jetstack/kube-lego#58]
We have 3 different stages of our app. They are all running on a different domain.
Each of them already obtained a ssl certificate and saved it as a secret.

This is a screenshot showing the **secrets**:

![screen shot 2016-11-16 at 11 50 07](https://cloud.githubusercontent.com/assets/2672413/20344390/d96664e8-abf2-11e6-889c-11904a84321a.jpg)

**But for only one of the stages** the ssl cert is actually set in the LoadBalancer. All others are only available through HTTP and not HTTP&HTTPS.

Here are all SSL certs available in the LoadBalancer settings:

![screen shot 2016-11-16 at 11 48 45](https://cloud.githubusercontent.com/assets/2672413/20344424/fcd07400-abf2-11e6-9432-5084ccf33c0f.jpg)

Any idea why it only adds one certificate to the Google Cloud Engine Network settings?

**Comment by thomas-mullaly** [comment]
If you're running all 3 stages of your app in the same cluster, you might be running into a known limitation with the GCE Ingress implementation. Specifically, the GCE Ingress doesn't support SNI, so it'll only ever configure 1 SSL certificate for the LoadBalancer. You can read more about it here: https://github.com/kubernetes/ingress/tree/master/controllers/gce#tls

**Comment by tsloughter** [comment]
Does this mean it would work if/when GCE Ingress supports SNI and nothing else would have to change?

**Comment by orian** [comment]
Just for notice, GCE Ingress supports SNI as today (2017.02.06).

**Comment by schurig** [comment]
works for me! 👍

**Comment by tsloughter** [comment]
@orian @schurig I can't find any reference to GCE SNI support, where have you found this?

**Comment by orian** [comment]
@tsloughter I'm using Kubernetes Ingress resource and it supports multiple domains and one certificate. I cannot recall where I've found it. But I find a Ingress spec very helpful (even bit more than a webpage doc): 
https://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/#_v1beta1_ingress

**Comment by tsloughter** [comment]
@orian yes, the ingress resource supports it but GCE LB does not (or at least hasn't worked for me and I can't find any docs saying it should work). The Kubernetes docs still say it is not supported: "This controller does not support SNI" from https://github.com/kubernetes/ingress/tree/master/controllers/gce
