### ISSUE TITLE
Is possible to use a different ingress controller?

### ISSUE THREAD

**Issue by aledbf** [jetstack/kube-lego#6]
Like gce

**Comment by simonswine** [comment]
Not my P1, but the next time I will have an GKE/GCE cluster running, I am gonna investigate a bit. 

I think every ingress object in k8s creates a separate forwarding rule in GCE, that will become an issue with the forwarding of the well-known paths.

**Comment by bprashanth** [comment]
Can we start with: https://github.com/kubernetes/contrib/pull/1289#discussion_r69826486? 
I think getting a well documented cross platform implementation will help more than something that works out of the box on a single platform. We should converge to a 0 user action cross platform model, but for that we'll need to declare that a given Ingress configures an existing IP/hostname explicitly (through a claim, like we do for volumes).

**Comment by simonswine** [comment]
@bprashanth the latest release of kube-lego 0.1.1, should support GCE ingress classes. (see the examples folder).

It handles the well-known acme endpoint on the original ingress and makes sure that there's a service inside the namespace with NodePort exposed. (It's modifying the endpoints for that in a selectorless service)

**Comment by bprashanth** [comment]
@simonswine fantastic! I'll give it a shot soon and let you know
