### ISSUE TITLE
404 on working auth

### ISSUE THREAD

**Issue by d1ngd0** [jetstack/kube-lego#70]
I keep getting a 404 error from my acme-challenge, even though I get 200 OK from my browser and in other browsers.

```
time="2016-12-29T19:56:57Z" level=info msg="no cert associated with ingress" context="ingress_tls" name=docker-registry namespace=default 
time="2016-12-29T19:56:57Z" level=info msg="requesting certificate for dr.paulmontag.info" context="ingress_tls" name=docker-registry namespace=default 
time="2016-12-29T19:56:59Z" level=debug msg="testing reachablity of http://dr.paulmontag.info/.well-known/acme-challenge/_selftest" context=acme domain=dr.paulmontag.info 
time="2016-12-29T19:57:00Z" level=debug msg="error while authorizing: reachabily test failed: wrong status code '404'" context=acme domain=dr.paulmontag.info
```

**Comment by nchudleigh** [comment]
I am also having this issue

**Comment by d1ngd0** [comment]
This error was happening for me because my router doesn't support a loopback feature. At least not in the Web UI.

The error `error while authorizing: reachabily test failed: wrong status code '404'` isn't coming from lets encrypt but actually from the kube-lego application itself. Because my DNS is all set up to point to my ISP supplied public ip address, when I try to access the application from inside my own network the packets go to the router and then get dropped. I wasn't noticing this outside of kubernetes because of some internal DNS I had set up which I won't go into because it isn't really relevant here.

So I guess my question for you nchudleigh is if you access a shell in one of your kubernetes containers and try pinging your domain name, what ip address do you see? If it is your home ip address can you access your sites from inside your lan? I might be getting ahead of myself as I am making a lot of assumptions about your setup :)

**Comment by zhengjia** [comment]
@d1ngd0 is correct. The 404 is from the perspective of the kube-lego container, not letsencrypt or your web browser.

You need to make sure the DNS is resolved to the correct IP address from the perspective of kube-lego. You could enter the container and run `nslookup DOMAIN` to figure that out. I noticed GCE sometimes take a long time to update the DNS records. Hope this helps.
