### ISSUE TITLE
"Error while process certificate requests"

### ISSUE THREAD

**Issue by srfrnk** [jetstack/kube-lego#77]
I tried to deploy using the GKE example. Didn't work.
Then using the NGNIX example (deployed on GKE) - still not working.
I can reach the service via HTTP but HTTPS reaches the default backend and then I can see these logs in the 'kube-lego-...' pod.

I've recreated the cluster a bunch of times nothing helped.
This is the entire set of files used to deploy (excl. code):
[k8s.zip](https://github.com/jetstack/kube-lego/files/699420/k8s.zip)

These are the pod logs:
```
time="2017-01-11T16:17:22Z" level=info msg="process certificates requests for ingresses" context=kubelego 
time="2017-01-11T16:17:22Z" level=info msg="creating new secret" context=secret name=dev-tls namespace=dev 
time="2017-01-11T16:17:22Z" level=info msg="no cert associated with ingress" context="ingress_tls" name=webapi namespace=dev 
time="2017-01-11T16:17:22Z" level=info msg="requesting certificate for api.dev.topside.io" context="ingress_tls" name=webapi namespace=dev 
time="2017-01-11T16:17:22Z" level=info msg="creating new secret" context=secret name=kube-lego-account namespace=kube-lego 
time="2017-01-11T16:17:23Z" level=info msg="creating new secret" context=secret name=dev-tls namespace=dev 
time="2017-01-11T16:17:23Z" level=error msg="Error while process certificate requests: Secret \"dev-tls\" is invalid: [data[tls.crt]: Required value, data[tls.key]: Required value]" context=kubelego
```

**Comment by maikotz** [comment]
Just having the same, could you share what you found out?

**Comment by whitecolor** [comment]
@maikotz how did you debug the problem and find out it?

**Comment by maikotz** [comment]
Hi @whitecolor for me it was just the cluster DNS which was not working. You can start a busybox pod and try to connect to the internet:
``kubectl run -i -t busybox --image=busybox --restart=Never --rm``

wget  https://acme-v01.api.letsencrypt.org

If you're able to ``ping 8.8.8.8`` but not to resolve acme-v01.api.letsencrypt.org, then your DNS is not running properly

**Comment by whitecolor** [comment]
Ah ok, I'm on GCE so it is probably not the case. Not sure why it doesn't work.

**Comment by srfrnk** [comment]
hey @whitecolor,

I can't really tell what was it that solved the issue for me cause I tried many combinations and finally the one that worked I'm pretty sure was tested and didn't work before.
I finally used the [nginx version](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx) which happened to work - also after many attempts.
Now I got a version that works consistently so if you're interested I can share the configuration files with you.

**Comment by tjkemper** [comment]
I did two things to fix it, and I'm pretty sure I needed both.
1) Ensure `kube-dns` is running on every node
2) Point the domain (dev.company.com) to the Load Balancer for the nginx ingress controller

I am on AWS though.  Hope this helps!
