### ISSUE TITLE
Health Check

### ISSUE THREAD

**Issue by Skilgarriff** [jetstack/kube-lego#8]
Would it be possible to build a Health Check into Kube-Lego itself? I feel like this would be a simplistic enough task, and it would allow the kubernetes server to use liveliness probes with kube-lego. If someone points me in the right direction, perhaps I could help with this.

**Comment by simonswine** [comment]
Hey @Skilgarriff sorry for my late respone. It's always a good idea to have an health check.

If you could take a look at it, would really be great. The current health check is not really doing anything:

https://github.com/jetstack/kube-lego/blob/master/pkg/acme/acme.go#L46

**Comment by simonswine** [comment]
I think the `/healthz` endpoint is good for now. Feel free to add a new ticket, when you discover a problem that is not cover by that or kube-lego restarting
