### ISSUE TITLE
No registration exists matching provided key

### ISSUE THREAD

**Issue by tsloughter** [jetstack/kube-lego#82]
I had a working GKE setup (kube-lego 0.1.3 using GCE LBs) that had successfully fetched certs for multiple domains a couple months ago.

Because of the fact that a gce load balancer can only handle 1 certificate it was overwriting the cert with each new domain added. This was fine at the time, this is just a testing environment, but now I wanted to force a particular domain to get a new cert so it would become the domain with a working cert. After deleting its cert and modifying the ingress kube-lego did start trying to get a new cert but now I have this in the logs and it fails:

```
authorization failed after 1m0s: getting authorization failed: 403 urn:acme:error:unauthorized: No registration exists matching provided key
```

Any idea how this could have happened and what I can do to fix it?

**Comment by tsloughter** [comment]
Sorry, accidentally submitted before finishing, I'm editing the issue now with the full details.

**Comment by tsloughter** [comment]
I deleted the `kube-lego-account` secret and the lego pod. The new pod then created a new account secret and everything worked.

I'll close this issue but it may be something to look into more to find out why this would happen and a way to not have it require this manual deletion?

**Comment by nick4fake** [comment]
Just trapped into exactly the same issue. kube-lego was installed via helm
